import numpy as np

def accel_del_waypoints(generated_path):
    """Function created to append additional waypoints to existing way points generated by the generated_path function.
    An "acceleration" waypoint is added into the waypoint sequence as the 2nd, 6th, 10th, etc iteration while the "deceleration" waypoint
    is added into the waypoint sequence as the 3rd, 7th, 11th, etc iteration. The accleration waypoint serves as an indication for the drone to 
    change its velocity to a variable speed while the deceleration waypoint serves as an indication for the drone to decrease its velocity to a 
    variable speed right before changing directions to pass the spline waypoint.
    
    Args:
        generated_path: numpy array of waypoints that are located at the edge of each transect indicating a change of direction.
        
    Returns:
        generated_path: updated generated path with acceleration and deceleration waypoints appended to original waypoint list."""
    
    generated_path = np.array(generated_path)
    acceleration_transect_distance = 0.25
    deceleration_transect_distance = 0.75

    new_waypoints = []

    for i in range(1, len(generated_path), 2):  # interpolation to gather acceleration and deceleration waypoints along transect
        direction_vector = generated_path[i] - generated_path[i-1]

        acceleration_waypoint = generated_path[i-1] + acceleration_transect_distance * direction_vector
        new_waypoints.append(acceleration_waypoint)

        deceleration_waypoint = generated_path[i-1] + deceleration_transect_distance * direction_vector
        new_waypoints.append(deceleration_waypoint)

    new_waypoints = np.array(new_waypoints)

    # concatenating new waypoints to original path planned waypoints
    acceleration_indices_to_modify = list(range(1, generated_path.shape[0]*2, 3))
    deceleration_indices_to_modify = list(range(2, generated_path.shape[0]*2, 4))

    for idx, waypoint in zip(acceleration_indices_to_modify, new_waypoints[::2]):
        generated_path = np.insert(generated_path, idx, waypoint, axis=0)

    for idx, waypoint in zip(deceleration_indices_to_modify, new_waypoints[1::2]):
        generated_path = np.insert(generated_path, idx, waypoint, axis=0)

    return generated_path