import numpy as np


def plan_mission(lat_long_turn_matrix, straight_velocity, turn_velocity):
    """Mission Planning function that creates a .waypoints file for Mission Planning reading
    This function takes in a 3 column array consisting of latitude, longitude, and turn status values pertaining to the generated path's waypoints.
    Using the data incorporated within the lat_long_turn matrix input, a 12 column matrix is created specifying information relating to the flight parameters
    at different waypoints.

    Args:
        lat_long_turn_matrix: 3 column numpy array consisting of latitude, longitude, and turn status values pertaining to the generated path's waypoints.
        The output generated by the turning_points function.

    Returns:
        new_Combine_2: finalized 12 column matrix that holds all flight specific parameters for each waypoint that will be read by Mission Planner.
        Output file is generated as a .txt file"""

    # Specify Flight Parameters

    Take_Off_Lat = 29.4048573
    Take_Off_Long = -82.1687382
    Travel_Speed = 3  # m/s
    Mission_Speed = 2.3  # m/s
    Slow_Mission_Speed = 1  # m/s
    Travel_Alt = 16  # m
    Mission_Alt = 8  # m

    # Raw Lat, Long, Turning Condition Data

    Raw_Input_Data = lat_long_turn_matrix
    Waypoint_Lat = Raw_Input_Data[:, 0]
    Waypoint_Long = Raw_Input_Data[:, 1]
    Waypoint_Turn_Index = Raw_Input_Data[:, 2]
    Waypoint_Number = np.arange(0, len(Waypoint_Lat))  # double check what purpose is

    # Creating Custom Core Mission File
    Core_Mission_Matrix = np.zeros((len(Waypoint_Lat), 12))

    Core_Mission_Matrix[:, 11] = 1  # just is idk
    Core_Mission_Matrix[:, 10] = Mission_Alt  # adds mission altitude
    Core_Mission_Matrix[:, 8] = Waypoint_Lat  # adds mission lat
    Core_Mission_Matrix[:, 9] = Waypoint_Long  # adds mission long
    Core_Mission_Matrix[:, 0] = Waypoint_Number + 9  # adds waypoint index number
    Core_Mission_Matrix[:, 2] = 3  # just is idk
    Core_Mission_Matrix[:, 3] = 16  # specifying the waypoints as waypoints in mission planner

    # Adding Specialty Turn Values
    Waypoint_Turn_Index = np.where(Waypoint_Turn_Index)[0]  # returning indices in vector that are '1'
    for i in Waypoint_Turn_Index:
        Core_Mission_Matrix[i, 3] = 82

    # Placeholder row for Straight and Turn Velocities
    placeholder_row = np.zeros((1, 12))
    placeholder_row[0, 2] = 3
    placeholder_row[0, 3] = 178  # indicating change of speed
    placeholder_row[0, 8] = 0  # latitude
    placeholder_row[0, 9] = 0  # longitude
    placeholder_row[0, 10] = Mission_Alt
    placeholder_row[0, 11] = 1

    Core_Mission_Matrix = Core_Mission_Matrix.astype(object)
    Core_Mission_Matrix[:, 3] = Core_Mission_Matrix[:, 3].astype(int)

    # Adding change of speed rows for straight velocity
    i = 1
    while i < len(Core_Mission_Matrix):
        if Core_Mission_Matrix[i, 3] == 16:
            placeholder_row[0, 5] = straight_velocity
            insert_position = i + 1
            Core_Mission_Matrix = np.insert(Core_Mission_Matrix, insert_position, placeholder_row, axis=0)
            i += 2
        if i < len(Core_Mission_Matrix) and Core_Mission_Matrix[i, 3] == 82:
            placeholder_row[0, 5] = turn_velocity
            insert_position = i + 1
            Core_Mission_Matrix = np.insert(Core_Mission_Matrix, insert_position, placeholder_row, axis=0)
            i += 2

    Core_Mission_Matrix = np.delete(Core_Mission_Matrix, -1, axis=0)

    # Readjusting Matrix indices

    column_size = Core_Mission_Matrix.shape[0]
    Core_Mission_Matrix[:, 0] = np.arange(column_size)

    # Adding Mission Start Parameters
    # Setting home
    Start_Mission_Matrix = np.zeros((6, 12))
    Start_Mission_Matrix[0, 1] = 1  # just is
    Start_Mission_Matrix[0, 3] = 16  # waypoint
    Start_Mission_Matrix[0, 8] = Take_Off_Lat  # lat
    Start_Mission_Matrix[0, 9] = Take_Off_Long  # long
    Start_Mission_Matrix[0, 11] = 1  # just is

    # Change Travel Speed
    Start_Mission_Matrix[1, 2] = 3  # just is
    Start_Mission_Matrix[1, 3] = 178  # Change Speed
    Start_Mission_Matrix[1, 5] = Travel_Speed  # Travel Speed
    Start_Mission_Matrix[1, 8] = 0  # lat
    Start_Mission_Matrix[1, 9] = 0  # long
    Start_Mission_Matrix[1, 10] = Travel_Alt  # Altitude to travel at
    Start_Mission_Matrix[1, 11] = 1  # just is

    # Take off
    Start_Mission_Matrix[2, 2] = 3  # just is
    Start_Mission_Matrix[2, 3] = 22  # Takeoff
    Start_Mission_Matrix[2, 5] = Travel_Speed  # Travel Speed NEW ADDITION
    Start_Mission_Matrix[2, 8] = Take_Off_Lat  # lat
    Start_Mission_Matrix[2, 9] = Take_Off_Long  # long
    Start_Mission_Matrix[2, 10] = Travel_Alt  # Altitude to travel at
    Start_Mission_Matrix[2, 11] = 1  # just is

    # Change Travel Speed
    Start_Mission_Matrix[3, 2] = 3  # just is
    Start_Mission_Matrix[3, 3] = 178  # Change Speed
    Start_Mission_Matrix[3, 5] = Travel_Speed  # Travel Speed
    Start_Mission_Matrix[3, 8] = 0  # lat
    Start_Mission_Matrix[3, 9] = 0  # long
    Start_Mission_Matrix[3, 10] = Travel_Alt  # Altitude to travel at
    Start_Mission_Matrix[3, 11] = 1  # just is

    # Travel to Mission Start Location
    Start_Mission_Matrix[4, :] = Core_Mission_Matrix[0, :]
    Start_Mission_Matrix[4, 2] = 3  # just is
    Start_Mission_Matrix[4, 3] = 16  # Waypoint
    Start_Mission_Matrix[4, 10] = 16  # Altitude to travel at
    Start_Mission_Matrix[4, 11] = 1  # just is

    # Change Travel Speed
    Start_Mission_Matrix[5, 2] = 3  # just is
    Start_Mission_Matrix[5, 3] = 178  # Change Speed
    Start_Mission_Matrix[5, 5] = Slow_Mission_Speed  # Travel Speed (CHANGED)
    Start_Mission_Matrix[5, 8] = 0  # lat
    Start_Mission_Matrix[5, 9] = 0  # long
    Start_Mission_Matrix[5, 10] = Travel_Alt  # Altitude to travel at
    Start_Mission_Matrix[5, 11] = 1  # just is

    # Drop Altitude to Mission Start Location
    filler_row = np.zeros((1, 12))
    Start_Mission_Matrix = np.vstack([Start_Mission_Matrix, filler_row])  # appending 7th row to matrix
    Start_Mission_Matrix[6] = Core_Mission_Matrix[0]
    Start_Mission_Matrix[6, 2] = 3  # just is
    Start_Mission_Matrix[6, 3] = 16  # Waypoint
    Start_Mission_Matrix[6, 10] = Mission_Alt  # Altitude to travel at
    Start_Mission_Matrix[6, 11] = 1  # just is

    # Change To Mission Speed
    filler_row = np.zeros((1, 12))
    Start_Mission_Matrix = np.vstack([Start_Mission_Matrix, filler_row])
    Start_Mission_Matrix[7, 2] = 3  # just is
    Start_Mission_Matrix[7, 3] = 178  # Change Speed
    Start_Mission_Matrix[7, 5] = Slow_Mission_Speed  # Mission Speed
    Start_Mission_Matrix[7, 8] = 0  # Lat
    Start_Mission_Matrix[7, 9] = 0  # Long
    Start_Mission_Matrix[7, 10] = Mission_Alt  # Altitude to travel at
    Start_Mission_Matrix[7, 11] = 1  # just is

    # Addition of slow start
    # Travel to Mission Start smid point Location
    filler_row = np.zeros((1, 12))
    Start_Mission_Matrix = np.vstack([Start_Mission_Matrix, filler_row])
    Start_Mission_Matrix[8] = Core_Mission_Matrix[0]
    Start_Mission_Matrix[8, 8] = ((Core_Mission_Matrix[1, 8] - Core_Mission_Matrix[0, 8]) / 2) + Core_Mission_Matrix[
        0, 8]
    Start_Mission_Matrix[8, 9] = ((Core_Mission_Matrix[1, 9] - Core_Mission_Matrix[0, 9]) / 2) + Core_Mission_Matrix[
        0, 9]
    Start_Mission_Matrix[8, 2] = 3  # just is
    Start_Mission_Matrix[8, 3] = 16  # Waypoint
    Start_Mission_Matrix[8, 10] = Mission_Alt  # Altitude to travel at
    Start_Mission_Matrix[8, 11] = 1  # just is

    # Change To Mission Speed
    filler_row = np.zeros((1, 12))
    Start_Mission_Matrix = np.vstack([Start_Mission_Matrix, filler_row])
    Start_Mission_Matrix[9, 2] = 3  # just is
    Start_Mission_Matrix[9, 3] = 178  # Change Speed
    Start_Mission_Matrix[9, 5] = Mission_Speed  # Mission Speed
    Start_Mission_Matrix[9, 8] = 0  # Lat
    Start_Mission_Matrix[9, 9] = 0  # Long
    Start_Mission_Matrix[9, 10] = Mission_Alt  # Altitude to travel at
    Start_Mission_Matrix[9, 11] = 1  # just is

    # Correcting the waypoint numbers
    Start_Mission_Matrix[:, 0] = np.arange(10)

    # Combining Start and Core Mission Sections
    Combine_1 = np.vstack((Start_Mission_Matrix, Core_Mission_Matrix[1:]))
    Combine_1[10:, 0] += 9
    End_Waypoint_Num = len(Combine_1)

    # Adding Mission End Parameters
    End_Mission_Matrix = np.zeros((4, 12))

    # Raise Altitude
    End_Mission_Matrix[0] = Core_Mission_Matrix[-1]
    End_Mission_Matrix[0, 2] = 3  # just is
    End_Mission_Matrix[0, 3] = 16  # Waypoint
    End_Mission_Matrix[0, 10] = 16  # Altitude to travel at
    End_Mission_Matrix[0, 11] = 1  # just is

    # Change To Travel Speed
    End_Mission_Matrix[1, 2] = 3  # just is
    End_Mission_Matrix[1, 3] = 178  # Change Speed
    End_Mission_Matrix[1, 5] = Travel_Speed  # Mission Speed
    End_Mission_Matrix[1, 8] = 0  # lat
    End_Mission_Matrix[1, 9] = 0  # long
    End_Mission_Matrix[1, 10] = Travel_Alt  # Altitude to travel at
    End_Mission_Matrix[1, 11] = 1  # just is

    # RTL
    End_Mission_Matrix[2] = Core_Mission_Matrix[0]
    End_Mission_Matrix[2, 5] = Travel_Speed  # Travel Speed
    End_Mission_Matrix[2, 2] = 3  # just is
    End_Mission_Matrix[2, 3] = 20  # RTL
    End_Mission_Matrix[2, 10] = 16  # Altitude to travel at
    End_Mission_Matrix[2, 11] = 1  # just is

    # Land
    End_Mission_Matrix[3, 2] = 3  # just is
    End_Mission_Matrix[3, 3] = 21  # Land
    End_Mission_Matrix[3, 10] = 0  # Altitude to travel at
    End_Mission_Matrix[3, 11] = 1  # just is

    # Correcting the waypoint numbers
    End_Mission_Matrix[:, 0] = np.arange(4) + End_Waypoint_Num

    # Combining Start, Core, and End Mission Sections
    # Startt string
    startt = 'QGC WPL 110\n'

    # Combine sections
    Combine_2 = np.vstack((Combine_1, End_Mission_Matrix))

    # Formatting Columns as necessary for Mission Planner
    new_Combine_2 = Combine_2.astype(object)

    new_Combine_2[:, 0:5] = Combine_2[:, 0:5].astype(int)  # first column to 5th column
    new_Combine_2[0:9, 5] = Combine_2[0:9, 5].astype(int)  # 5th column, rows 0 - 8
    new_Combine_2[10:, 5] = Combine_2[10:, 5].astype(int)  # 5th column, rows 10 - end
    new_Combine_2[:, 6:8] = Combine_2[:, 6:8].astype(int)  # 6th column to 8th column
    new_Combine_2[1:10:2, 8:10] = Combine_2[1:10:2, 8:10].astype(int)  # formatting rows of 8th column & 9th column
    new_Combine_2[:, 10:] = Combine_2[:, 10:].astype(int)  # formatting all rows of 10th and 11th column
    return new_Combine_2

def main():
    from LatLongTurn_Integrated_Code import bi_linear_interpolation
    from LatLongTurn_Integrated_Code import turning_points

    # GUI Values - for testing purposes
    ref_pix = np.array([
        [342, 145],
        [827, 493],
        [523, 143],
        [378, 590],
    ])
    ref_lla = np.array([
        [29.408446, -82.170371],
        [29.407492, -82.168867],
        [29.408435, -82.169896],
        [29.407235, -82.170208]
    ])
    points = np.column_stack((ref_pix, ref_lla))

    reference_points = np.array(points)

    generated_path = np.array([
        [780.00, 542.60],
        [806.89, 496.02],
        [809.42, 456.07],
        [755.63, 549.23],
        [740.22, 540.34],
        [811.94, 416.12],
        [805.50, 391.70],
        [715.85, 546.97],
        [691.48, 553.60],
        [808.03, 351.75],
        [801.59, 327.32],
        [676.08, 544.71],
        [651.71, 551.34],
        [804.11, 287.37],
        [797.67, 262.95],
        [627.34, 557.98],
        [611.93, 549.08],
        [773.30, 269.59],
        [757.90, 260.69],
        [587.56, 555.72],
        [572.16, 546.82],
        [742.49, 251.80],
        [727.09, 242.90],
        [547.79, 553.46],
        [523.42, 560.09],
        [702.72, 249.54],
        [705.24, 209.59],
        [508.01, 551.20],
        [483.64, 557.83],
        [698.80, 185.17],
        [683.40, 176.27],
        [459.27, 564.46],
        [434.90, 571.10],
        [667.99, 167.38],
        [652.59, 158.48],
        [419.50, 562.20],
        [395.13, 568.83],
        [628.22, 165.12],
        [612.81, 156.22],
        [388.69, 544.41],
        [382.25, 519.99],
        [588.44, 162.86],
        [564.07, 169.49],
        [384.77, 480.04],
        [387.30, 440.09],
        [548.67, 160.60],
        [524.30, 167.23],
        [389.82, 400.14],
        [383.38, 375.72],
        [499.93, 173.86],
        [484.52, 164.97],
        [385.91, 335.77],
        [388.43, 295.82],
        [460.15, 171.60],
        [435.78, 178.24],
        [390.96, 255.87],
        [384.52, 231.45],
        [411.41, 184.87],
        [396.01, 175.98],
        [378.08, 207.03]
    ])  # updated default planned path

    latitude_longitude_interpolation = bi_linear_interpolation(reference_points, generated_path)
    lat_long_turn = turning_points(generated_path, latitude_longitude_interpolation)

    plan_mission(lat_long_turn, straight_velocity=3, turn_velocity=5)

if __name__ == '__main__':
    main()